name: CropDiaryMobile CI

on:
  push:
    branches: [ "feat", "master" ]
    paths:
      - '**/*'          # It will be executed if there are changes anywhere in the project except the tests folder
      - '!app/src/test/**'  # Will exclude the tests folder from the workflow
      - '!app/src/androidTest/**'  # Will exclude the instrumentation tests folder from the workflow

  pull_request:
    branches: [ "feat", "master"]
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build app
        run: ./gradlew assemble